feat: Mention community images in reference
citynetwork/docs pull request #213
Opened 2023-07-13 08:44 UTC by noonedeadpunk

We have recently switched our image rotation mechanism from
deactivating the image, which makes impossible any futher usage of the
image, to marking them as "comminuty" ones. This allows to use
already rotated image in case of need. Potential usecases are:
* Server rebuild
* New images somehow misbehave
* User will to use exact same image for another VM in the cluster

While usage of community images is inadvisable, we still should
mention their existance.

2023-08-16 13:18 UTC, fghaas commented
@noonedeadpunk, I believe this documentation update is no longer in line with how we manage images. Is that correct? If so, should we close this one?

2023-08-16 15:07 UTC, fghaas commented
Okay, can you please squash those two commits into one, and also rebase them on current `main`, before we review?

2023-08-16 15:24 UTC, noonedeadpunk commented
done

2023-08-16 15:47 UTC, fghaas requested changes
Thanks, I have a few suggestions for this one. :)

2023-08-16 15:47 UTC, fghaas commented on docs/reference/images/index.md
> +At {{brand}} we regulary update and rotate our images to always provide
```suggestion
At {{brand}}, we regularly update and rotate our images to always provide
```

2023-08-16 15:47 UTC, fghaas commented on docs/reference/images/index.md
> +Terraform to pass validation checks without attempting to alter environments.
```suggestion
During rotation, we change an image's visibility from `public` to `community`, while
keeping its image name. This enables tools like [Heat](https://docs.openstack.org/heat/)
or [Terraform](https://www.terraform.io/) to pass validation checks without attempting to alter environments.
```

2023-08-16 15:47 UTC, fghaas commented on docs/reference/images/index.md
> +`YYYY-mm-dd` format.
```suggestion
You can retrieve an image's original build date (for both `public` and `community` images)
by checking its `build_date` tag or `image_build_date` property.
```

2023-08-16 16:25 UTC, noonedeadpunk commented
> Not quite; topic branch wasn't rebased on current state of `main`. :) I've taken care of that now.

Ah, true, I've fetched upstream, rebased main on top of upstream/main, pushed main to origin/main, but then didn't rebase that on top of origin/main... When trivial rebase requires 5 steps to execute, it's not hard for things to slip :(

2023-08-17 07:44 UTC, fghaas commented
I don't quite see 5 steps?

```bash
git checkout bugfix/community_images
git fetch upstream main:main
git rebase main
```

But if even 3 is too much, a clean rebase on current upstream `main` amounts to two clicks here in the web interface. :)

2023-08-17 13:00 UTC, merged