feat: Add How-To rescue server
citynetwork/docs pull request #83
Opened 2022-12-07 13:02 UTC by ahosam

As continue of [CLDENG-846](https://jira.citynetwork.se/browse/CLDENG-846) starting by this HowTo for Rescue Server. 
This guide will walk you through the required steps to access the the rescue mode when you need to, 
more comments will be add it once both [RD-2723](https://jira.citynetwork.se/browse/RD-2723) & [RD-2714](https://jira.citynetwork.se/browse/RD-2714) is implemented

2022-12-07 13:23 UTC, fghaas commented
@ahosam Before we start reviewing this, please add a proper commit message body, and update your PR description. Do not refer to internal ticket references in doing so; this is a public project that we want to keep free of internal-only references.

2022-12-07 14:15 UTC, noonedeadpunk commented on docs/howto/openstack/nova/rescue-server.md
> +    openstack server rescue <server_id>
I think this method should fail for BFV instances. We should be explicit on when to use rescue image. Given that these docs are not actually considering non-BFV, not sure we should even mention this (unless I'm wrong and bfv instances can boot with base image)

2022-12-12 15:15 UTC, fghaas requested changes
Please remove everything in the `site` directory from your commit. All that content is automatically generated by the CI platform, and does not belong in the repo.

2022-12-19 16:18 UTC, fghaas commented
@ahosam I've taken the liberty to give this a rewrite, and @colder-is-better and I will now proceed with the review.

2022-12-19 17:39 UTC, colder-is-better reviewed
Besides the fact that I'm not a big fan of taking screenshots of small graphical elements, like the three-dot icon or the logo-with-exclamation-mark icon, everything else looks good to me :)

2022-12-20 08:16 UTC, fghaas approved these changes
OK, then let's go ahead and merge this now. :)

2022-12-20 08:17 UTC, merged

2022-12-20 08:40 UTC, noonedeadpunk commented
You're so fast @fghaas :-)

I was going to say, that we'd need to mention on how to upload own rescue image in terms of properties that should be set for such image to work nicely, such as
```
hw_rescue_bus=virtio
hw_rescue_device=disk 
```

We also tag such images as `system-rescue` for purpose of this doc (being able to filter) and I expect CCP to implement filtering on this tag as well in the future.

I can't propose follow up patch right now due to ENOTIME, so have to ask you or @ahosam for adding section of adding own rescue images.

2022-12-20 08:44 UTC, fghaas commented
@noonedeadpunk Do we want to encourage that though? As in, do we want to suggest that people use a different rescue image from the one we test make available publicly?

2022-12-20 09:25 UTC, noonedeadpunk commented
@fghaas I'm not sure that systemrescuecd covers all use-cases, let's say, for Windows recovery. As  I can imagine that ppl might want some specific recovery image that we don't have (or don't want to have) at the moment.
Also systemrescuecd used to have quite tricky way for installing additional tools that were needed occasionally (but quite rarely). They've switched underlying OS from Gentoo to smth else since then (haven't used it a lot lately), so likely it's not the case as of today.
But still I don't see an issue of having custom recovery images if clients are willing so. And this enables CE to point to docs if they're unhappy with what we have.